import { Customer, User, ActivityLog } from '../types';

export const mockUsers: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@crm.com', role: 'admin', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin' },
  { id: '2', name: 'John Employee', email: 'john@crm.com', role: 'employee', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John' },
  { id: '3', name: 'Sarah Manager', email: 'sarah@crm.com', role: 'senior_manager', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
];

export const mockCustomers: Customer[] = [
  {
    id: '1',
    customer_code: 'CUST-001',
    name: 'Alice Johnson',
    contact_number: '+1 234-567-8901',
    service_type: 'Technical Support',
    call_status: 'responded',
    response_notes: 'Resolved issue with login.',
    service_done: true,
    forward_to_senior: false,
    assigned_employee_id: '2',
    assigned_employee_name: 'John Employee',
    date_time: '2023-10-24T10:30:00Z',
  },
  {
    id: '2',
    customer_code: 'CUST-002',
    name: 'Bob Smith',
    contact_number: '+1 234-567-8902',
    service_type: 'Billing Inquiry',
    call_status: 'pending',
    response_notes: '',
    service_done: false,
    forward_to_senior: false,
    assigned_employee_id: '2',
    assigned_employee_name: 'John Employee',
    date_time: '2023-10-24T11:15:00Z',
  },
  {
    id: '3',
    customer_code: 'CUST-003',
    name: 'Charlie Brown',
    contact_number: '+1 234-567-8903',
    service_type: 'Product Demo',
    call_status: 'forwarded',
    response_notes: 'Customer needs complex enterprise integration details.',
    service_done: false,
    forward_to_senior: true,
    assigned_employee_id: '3',
    assigned_employee_name: 'Sarah Manager',
    date_time: '2023-10-24T09:00:00Z',
  },
  {
    id: '4',
    customer_code: 'CUST-004',
    name: 'Diana Prince',
    contact_number: '+1 234-567-8904',
    service_type: 'Warranty Claim',
    call_status: 'not_responded',
    response_notes: 'Tried calling 3 times, no answer.',
    service_done: false,
    forward_to_senior: false,
    assigned_employee_id: '2',
    assigned_employee_name: 'John Employee',
    date_time: '2023-10-23T14:20:00Z',
  },
  {
    id: '5',
    customer_code: 'CUST-005',
    name: 'Ethan Hunt',
    contact_number: '+1 234-567-8905',
    service_type: 'General Inquiry',
    call_status: 'responded',
    response_notes: 'Information provided about new features.',
    service_done: true,
    forward_to_senior: false,
    assigned_employee_id: '2',
    assigned_employee_name: 'John Employee',
    date_time: '2023-10-23T16:45:00Z',
  },
];

export const mockLogs: ActivityLog[] = [
  { id: '1', user_id: '1', user_name: 'Admin User', action: 'Login', details: 'User logged into the system', created_at: '2023-10-24T08:00:00Z' },
  { id: '2', user_id: '2', user_name: 'John Employee', action: 'Customer Update', details: 'Updated status for Alice Johnson', created_at: '2023-10-24T10:45:00Z' },
  { id: '3', user_id: '2', user_name: 'John Employee', action: 'Case Forwarded', details: 'Forwarded Charlie Brown to Sarah Manager', created_at: '2023-10-24T09:15:00Z' },
];
